"""
NeuralPulse 2.0 - Fast Fine-Tuning Script (Unsloth).

Run this on Google Colab (Free Tier T4 GPU) or Local WSL2 (Recommended for Windows).
Model: Llama-3.2-1B-Instruct (Optimized for 4GB VRAM)

Steps:
1. Install unsloth: pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
2. Upload 'reasoning_dataset.jsonl' (Generated by synthesizer).
3. Run this script.
4. Download 'neuralpulse_lora' folder.
"""

# START CODE
import torch
import os
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# Define the Prompt Style (Alpaca-style works well for generic instruction following)
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""


def train():
    # 1. Config for 4GB VRAM
    max_seq_length = 1024  # Reduced from 2048 to save memory
    dtype = None
    load_in_4bit = True

    print("🚀 Loading Llama-3.2-1B...")
    # 2. Load Base Model
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="unsloth/Llama-3.2-1B-Instruct",
        max_seq_length=max_seq_length,
        dtype=dtype,
        load_in_4bit=load_in_4bit,
    )

    # 3. Add LoRA Adapters
    model = FastLanguageModel.get_peft_model(
        model,
        r=8,  # Reduced rank for memory safety on 3050
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj", ],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
        use_rslora=False,
        loftq_config=None,
    )

    # 4. Load Dataset
    print("📂 Loading dataset...")

    # We define a formatting function to combine Instruction + Input + Output
    def formatting_prompts_func(examples):
        instructions = examples["instruction"]
        inputs = examples["input"]
        outputs = examples["output"]
        texts = []
        for instruction, input, output in zip(instructions, inputs, outputs):
            # Must add EOS token, otherwise generation goes on forever!
            text = alpaca_prompt.format(instruction, input, output) + tokenizer.eos_token
            texts.append(text)
        return {"text": texts}

    # Ensure this file is in the same folder!
    # Using 'reasoning_dataset.jsonl' per config, but generic 'json' loader handles lists/jsonl
    dataset_path = "reasoning_dataset.jsonl"
    if not os.path.exists(dataset_path):
        # Fallback if user named it .json
        dataset_path = "reasoning_dataset.json"

    dataset = load_dataset("json", data_files=dataset_path, split="train")
    dataset = dataset.map(formatting_prompts_func, batched=True)

    # 5. Trainer
    print("🚂 Starting Training...")
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",  # Now we use the formatted text column
        max_seq_length=max_seq_length,
        dataset_num_proc=2,
        args=TrainingArguments(
            per_device_train_batch_size=2,  # Low batch size for 4GB VRAM
            gradient_accumulation_steps=4,  # Simulate batch size of 8
            warmup_steps=5,
            max_steps=60,  # Quick fine-tune
            learning_rate=2e-4,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=1,
            output_dir="outputs",
            optim="adamw_8bit",  # Saves VRAM
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
        ),
    )

    # 6. Train
    trainer.train()

    # 7. Save
    print("💾 Saving Adapter...")
    model.save_pretrained("neuralpulse_lora")
    tokenizer.save_pretrained("neuralpulse_lora")
    print("✅ Model Saved to 'neuralpulse_lora'")


if __name__ == "__main__":
    try:
        train()
    except ImportError:
        print("❌ Error: 'unsloth' not found. If on Windows, please run this inside WSL2.")
    except Exception as e:
        print(f"Error: {e}")